# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ru
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: KerasPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
  - name: FormPolicy
  - name: MappingPolicy
  
